FROM nvcr.io/nvidia/tlt-streamanalytics:v1.0_py2

COPY tlt_ssd.ipynb /workspace/examples/ssd/

RUN mkdir /workspace/examples/ssd/tlt_figures/
COPY tlt_figures/* /workspace/examples/ssd/tlt_figures/

WORKDIR /workspace/
